version: 0.0

os: linux
files:
  - source: src/web/app/app.war
    destination: /opt/jetty-base/webapps/
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    
hooks:
  ApplicationStop:
    - location: scripts/stop-jetty.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/bfore_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set-permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start-jetty.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate-service.sh
      timeout: 300
      runas: root
