version: 0.0
os: linux
files:
  - source: target/geostore.war
    destination: /var/www/html/geostore.war
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
