version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing dependencies...
      - sudo apt-get update
      - sudo apt-get install -y maven git
  pre_build:
    commands:
      - echo Changing directory to src...
      - cd src
  build:
    commands:
      - echo Building the GeoStore application...
      - mvn clean install
      - echo Changing directory to src/web/app...
      - cd web/app
    #  - mvn jetty:run
  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - src/web/app/target/*.war
    - '**/*'
  base-directory: src/web/app
  
    
